# NumPy in Python

## NumPy (Numerical Python) is a fundamental library for numerical and scientific computing in Python. It provides:

* Ndarray: A powerful n-dimensional array object for efficient storage and manipulation of large datasets.
* Mathematical Functions: A comprehensive suite of mathematical functions to operate on arrays.
* Broadcasting: A mechanism to perform operations on arrays of different shapes.
* Linear Algebra: Support for linear algebra operations, such as matrix multiplication and decompositions.
* Random Number Generation: Tools for generating random numbers and sampling from distributions.
* Performance: Highly optimized for speed with many operations implemented in C.

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


## if we to see the timing results.

In [163]:
# For array taken time

# %timeit [j**4 for j in range(1,9)]

In [164]:
# For list taken time: 

# %timeit np.arange(1,9)**4

In [173]:
# for array... we can check datatype
import numpy as np
x = np.array([1,2,3,4])
# index       0,1,2,3,4,5,6,7,8,9
print("Example of Array: ",x)
# we can check  the datatype 
print("Type of this variable: ",type(x))

Example of Array:  [1 2 3 4]
Type of this variable:  <class 'numpy.ndarray'>


In [174]:
# for  list..................
list1 = [1,2,3,4]
# index  0,1,2,3,4,5,6,7,8,9
print("Example of List: ",list1)
# we can check  the datatype 
print("Type of this variable: ",type(list1))

Example of List:  [1, 2, 3, 4]
Type of this variable:  <class 'list'>


# CREATION NUMPY ARRAYS

## Creating Arrays with a Range of Elements
* In NumPy, you can use the np.arange function to create arrays with a range of elements. 
* This function works similarly to Python's built-in range function but returns a NumPy array.

In [2]:
import numpy as np
a = np.array([1,2,3])
# index number    0,1,2,3,4,5,6,7,8,9
print(a)

# Create an array with elements from 0 to 9
arr1 = np.arange(10)
print("arr1: ",arr1)  # Output: [0 1 2 3 4 5 6 7 8 9]

# Create an array with elements from 5 to 14
arr2 = np.arange(5, 15)
print("arr2: ",arr2)  # Output: [ 5  6  7  8  9 10 11 12 13 14]

# Create an array with elements from 0 to 10 with a step of 2
arr3 = np.arange(0, 11, 2)
print("arr3: ",arr3)  # Output: [ 0  2  4  6  8 10]



[1 2 3]
arr1:  [0 1 2 3 4 5 6 7 8 9]
arr2:  [ 5  6  7  8  9 10 11 12 13 14]
arr3:  [ 0  2  4  6  8 10]


## Appending Elements to a NumPy Array
In NumPy, you can use the np.append function to append elements to an array. 
The np.append function does not modify the original array but returns a new array with the appended elements.

In [178]:

import numpy as np

# Create an initial array
array = np.array([1, 2, 3, 4])
print("Original array:", array)  # Output: [1 2 3 4]

# Append a single element to the array
array = np.append(array, 5)
print("Array after appending 5:", array)  # Output: [1 2 3 4 5]

# Append multiple elements to the array
array = np.append(array, [6, 7, 8])
print("Array after appending [6, 7, 8]:", array)  # Output: [1 2 3 4 5 6 7 8]

Original array: [1 2 3 4]
Array after appending 5: [1 2 3 4 5]
Array after appending [6, 7, 8]: [1 2 3 4 5 6 7 8]


 One dimention array:

## Dimension and Datatype of this array:  
if we want to see the datatype then we use type() function 
also, we can check the dimension of the array.

In [179]:
    import numpy as np
# One dimension array
    x = np.array([1,2,3,4])
# index number    0,1,2,3,4,5,6,7,8,9
    print(x)
    print("Data Type of this Array : ",type(x))   # here we use type function for checking the data type of this array
    print(" ONE-Dimention of this Array: ",x.ndim)

# Two dimention array:
    y = np.array([[1,2,3,4],[4,5,6,7]])
    print(y)
    print(" TWO-Dimention of this Array: ",y.ndim)

# Three dimention array:
    z = np.array([[[1,2,3,4],[4,5,6,7]]])
    print(z)
    print(" THREE-Dimention of this Array: ",z.ndim)

[1 2 3 4]
Data Type of this Array :  <class 'numpy.ndarray'>
 ONE-Dimention of this Array:  1
[[1 2 3 4]
 [4 5 6 7]]
 TWO-Dimention of this Array:  2
[[[1 2 3 4]
  [4 5 6 7]]]
 THREE-Dimention of this Array:  3


 # Special NumPy Array

## Array filled with Zero's

In NumPy, you can create arrays filled with zeros using the np.zeros function. This function is useful when you need an array of a specific size but don't have the initial values yet. Here's how you can use it:

In [158]:
# Creating Arrays Filled with Zeros


# One-Dimensional Array:
import numpy as np
# Create a one-dimensional array with 5 zeros
arr1 = np.zeros(5)
print("One-Dimensional Array: ",arr1)  # Output: [0. 0. 0. 0. 0.]


# Two-Dimensional Array:
import numpy as np
# Create a 2x3 array filled with zeros
arr2 = np.zeros((2, 3))
print("Two-Dimensional Array: ",arr2)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]


# Three-Dimensional Array:
import numpy as np
# Create a 2x3x4 array filled with zeros
arr3 = np.zeros((2, 3, 4))
print("Three-Dimensional Array: ",arr3)
# Output:
# [[[0. 0. 0. 0.]
#   [0. 0. 0. 0.]
#   [0. 0. 0. 0.]]
#
#  [[0. 0. 0. 0.]
#   [0. 0. 0. 0.]
#   [0. 0. 0. 0.]]]

One-Dimensional Array:  [0. 0. 0. 0. 0.]
Two-Dimensional Array:  [[0. 0. 0.]
 [0. 0. 0.]]
Three-Dimensional Array:  [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Creating Arrays Filled with Ones:
In NumPy, you can create arrays filled with ones using the np.ones function. 
This function is similar to np.zeros but initializes the array with ones instead of zeros. 
Here are examples of how to create arrays filled with ones:

In [161]:
# One-Dimensional Array: 
import numpy as np
# Create a one-dimensional array with 5 ones
array = np.ones(5)
print("One-Dimensional Array: ",array)  # Output: [1. 1. 1. 1. 1.]

# Two-Dimensional Array:
import numpy as np
# Create a 2x3 array filled with ones
array = np.ones((2, 3))
print("Two-Dimensional Array: ",array)
# Output:
# [[1. 1. 1.]
#  [1. 1. 1.]]

# Three-Dimensional Array:
import numpy as np

# Create a 2x3x4 array filled with ones
array = np.ones((2, 3, 4))
print("Three-Dimensional Array: ",array)
# Output:
# [[[1. 1. 1. 1.]
#   [1. 1. 1. 1.]
#   [1. 1. 1. 1.]]
#
#  [[1. 1. 1. 1.]
#   [1. 1. 1. 1.]
#   [1. 1. 1. 1.]]]

One-Dimensional Array:  [1. 1. 1. 1. 1.]
Two-Dimensional Array:  [[1. 1. 1.]
 [1. 1. 1.]]
Three-Dimensional Array:  [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [162]:
# Specifying the Data Type
#You can also specify the data type of the ones in the array using the dtype parameter.
import numpy as np

# Create a one-dimensional array with 5 ones of integer type
array = np.ones(5, dtype=int)
print(array)  # Output: [1 1 1 1 1]

[1 1 1 1 1]


Summary
* One-Dimensional Array: np.ones(n) creates a 1D array with n ones.
* Two-Dimensional Array: np.ones((m, n)) creates a 2D array with m rows and n columns, filled with ones.
* Three-Dimensional Array: np.ones((p, m, n)) creates a 3D array with p layers, m rows, and n columns, filled with ones.
* Data Type: Use the dtype parameter to specify the type of the ones (e.g., int, float).


  These functions are useful for initializing arrays for various applications, such as creating matrices for mathematical operations, setting up grids for simulations, or generating placeholder arrays for data processing.

## Create an empty array: 
In NumPy, you can create an empty array using the np.empty function. This function creates an array without initializing its entries, 
which means the array will contain whatever values were already in memory at that location.


* np.empty(3) creates a 1-dimensional array with 3 elements.
* np.empty((2, 3)) creates a 2-dimensional array with 2 rows and 3 columns.
* np.empty((2, 2, 3)) creates a 3-dimensional array with dimensions 2x2x3.


In [182]:
import numpy as np

# Creating a 1-dimensional empty array with 3 elements
empty_array_1d = np.empty(3)
print("empty_array_1d: ",empty_array_1d)

# Creating a 2-dimensional empty array with 2 rows and 3 columns
empty_array_2d = np.empty((2, 3))
print("empty_array_2d: ",empty_array_2d)

# Creating a 3-dimensional empty array with dimensions 2x2x3
empty_array_3d = np.empty((2, 2, 3))
print("empty_array_3d: ",empty_array_3d)


empty_array_1d:  [4.24399158e-314 1.27319747e-313 2.12199579e-313]
empty_array_2d:  [[0. 0. 0.]
 [0. 0. 0.]]
empty_array_3d:  [[[8.73510143e-312 2.96439388e-322 0.00000000e+000]
  [0.00000000e+000 1.06099790e-312 1.50008929e+248]]

 [[4.31174539e-096 1.15998412e-028 3.77778426e+180]
  [1.15998412e-028 4.19462329e+228 1.55535091e+161]]]


## Eye Function in NumPy Array: 
The numpy.eye function creates a 2-D array with ones on the diagonal and zeros elsewhere. This is often used to create an identity matrix.

Here's the basic syntax for np.eye:    numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
* N: Number of rows in the output array.
* M: Number of columns in the output array. If None, defaults to N (i.e., it creates a square matrix).
* k: Index of the diagonal. 0 (default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value refers to a lower diagonal.
* dtype: Data type of the output array.
* order: Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.


In [184]:
import numpy as np
ar_dia = np.eye(3)
print("Creating a square identity matrix: ",ar_dia)
print()
ar_dia1 = np.eye(3,5)
print("Creating a rectangular matrix with ones on the main diagonal: ", ar_dia1)

Creating a square identity matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Creating a rectangular matrix with ones on the main diagonal:  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Linspace IN NUMPY ARRAY
In NumPy, you can create an array of evenly spaced values over a specified range using the numpy.linspace() function.

The syntax for numpy.linspace() is:
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)




* start: The starting value of the sequence.
* stop: The end value of the sequence.
* num: Number of samples to generate. Default is 50.
* endpoint: If True (default), stop is the last sample. If False, stop value is not included.
* retstep: If True, return (samples, step), where step is the spacing between samples.
* dtype: The data type of the output array.
* axis: The axis in the result to store the samples. If None, the result is flattened.

In [185]:
import numpy as np 
ar_lin1 = np.linspace(1,10,num=5)


ar_lin2 = np.linspace(0,10,num=5)
ar_lin3 = np.linspace(1,20,num=5)
ar_lin4 = np.linspace(0,20,num=5)
ar_lin5 = np.linspace(5,30,num=10)
ar_lin6 = np.linspace(0,200,num=100)
print(ar_lin1)
print(ar_lin2)
print(ar_lin3)
print(ar_lin4)
print(ar_lin5)
print(ar_lin6)

[ 1.    3.25  5.5   7.75 10.  ]
[ 0.   2.5  5.   7.5 10. ]
[ 1.    5.75 10.5  15.25 20.  ]
[ 0.  5. 10. 15. 20.]
[ 5.          7.77777778 10.55555556 13.33333333 16.11111111 18.88888889
 21.66666667 24.44444444 27.22222222 30.        ]
[  0.           2.02020202   4.04040404   6.06060606   8.08080808
  10.1010101   12.12121212  14.14141414  16.16161616  18.18181818
  20.2020202   22.22222222  24.24242424  26.26262626  28.28282828
  30.3030303   32.32323232  34.34343434  36.36363636  38.38383838
  40.4040404   42.42424242  44.44444444  46.46464646  48.48484848
  50.50505051  52.52525253  54.54545455  56.56565657  58.58585859
  60.60606061  62.62626263  64.64646465  66.66666667  68.68686869
  70.70707071  72.72727273  74.74747475  76.76767677  78.78787879
  80.80808081  82.82828283  84.84848485  86.86868687  88.88888889
  90.90909091  92.92929293  94.94949495  96.96969697  98.98989899
 101.01010101 103.03030303 105.05050505 107.07070707 109.09090909
 111.11111111 113.13131313 115.1515151

# Create Numpy Arrays with Random Numbers

* rand(): the function is used to generate a random value between 0 to 1.
* randn(): the function is used to generate a random value close to zero.
            This may  return positive or negetive numbers as well.
* ranf(): the function for doing random sampling in numpy. It returns an array of specific shape and fills it with random floats.
            in the half open interval [0.0,1.0]
* randint(): the function is used to generate a random number be in a given range.


In [189]:
import numpy as np

# Generate a 1D array of 5 random numbers
random_values1 = np.random.rand(5)
print(random_values1)
print()

# Generate a 2x3 array of random values from a normal distribution
random_values2 = np.random.randn(2, 3)
print(random_values2)
print()
# Generate a 3x2 array of random floats
random_values3 = np.random.ranf((3, 2))
print(random_values3)


[0.39224245 0.73088258 0.84180443 0.46912904 0.5258451 ]

[[ 0.91998084 -1.03745072  0.93101628]
 [-0.90576988  0.51414556 -1.3022233 ]]

[[0.64908094 0.31818693]
 [0.04927275 0.04780101]
 [0.83818851 0.87401924]]


In [20]:
ar_var1 = np.random.randn(1000)
print(ar_var1)

[-4.43759079e-01  1.67365137e-01  1.45949912e+00  8.53003138e-01
  1.52843596e-01 -1.08579734e+00  1.06132247e+00 -5.32890760e-01
 -7.75217765e-01  3.09060313e-01 -1.04420090e+00 -2.94999546e-01
 -6.14251558e-01 -2.00656763e-01  4.05197425e-01  2.15041056e-01
 -1.60974664e+00 -4.77526668e-01  1.15457549e+00  1.84813610e-01
 -1.24626752e+00 -4.09053052e-01 -1.66493435e+00 -6.31810480e-01
 -1.35863138e+00 -6.51683207e-01  3.61140137e-01  1.92377637e+00
  6.87377293e-01  4.25820825e-01  8.11903625e-01 -2.23609885e-01
 -3.70491712e-01 -5.16825733e-01 -6.24893557e-01  1.28716137e-01
 -7.79265066e-01 -2.57533292e-01 -1.51964900e-01  3.33269689e-01
 -5.24483733e-01  8.61461596e-01  1.13111553e+00 -4.34114686e-01
 -4.02612914e-01 -1.01583058e+00  1.97836909e+00 -1.53404423e+00
 -1.73015382e+00 -1.06990788e+00 -1.11304266e+00 -5.78580428e-01
  5.65977873e-01 -6.07681152e-01  8.17194284e-01  1.74302485e+00
 -1.29347331e+00  4.76164671e-01  2.23628397e-01 -3.86787486e-01
  4.34742693e-01  6.57550

# Data Type in Numpy Array

1. bool_  ----------------------------------  Boolean (True or False) stored as a byte

2. int_    ---------------------------------      Default integer type (same as C long; normally either int64 or int32)

3. intc   --------------------------Identical to C int (normally int32 or int64)

4. intp    ------------------------      Integer used for indexing (same as C ssize_t; normally either int32 or int64)

5. int8    ------------------------------    Byte (-128 to 127)

6. int16  -------------------------------------    Integer (-32768 to 32767)

7. int32  -----------------------------------------Integer (-2147483648 to 2147483647)

8. int64  ----------------------------------------   Integer (-9223372036854775808 to 9223372036854775807)

9. uint8  --------------------------------------     Unsigned integer (0 to 255)

10. uint16 ------------------------------------     Unsigned integer (0 to 65535)

11. uint32 ------------------------------------       Unsigned integer (0 to 4294967295)

12. uint64 ---------------------------     Unsigned integer (0 to 18446744073709551615)

13. float_ -----------------------    Shorthand for float64

14. float16  ----------------------------  Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

15.float32       --------------------------Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

16. float64    -------------------------------Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

17. complex_  ---------------------------------------Shorthand for complex128

18. complex64   ---------------------------------------Complex number, represented by two 32-bit floats (real and imaginary components)

19. complex128  --------------------------------------    Complex number, represented by two 64-bit floats (real and imaginary components)

## Data Types as Function

list of characters that are used to represent dtype in Numpy:

* i- integer
* b- boolean
* u- unsigned integer
* f- float
* C- complex float
* m- timedelta
* M- datetime
* 0- object
* S- string
* U-Unicode string
* V- the fixed chunk of memory for other types (void)

In [8]:
# Integer (i):
import numpy as np
# Creating an array of integers
arr_int = np.array([1, 2, 3], dtype='i')
print(arr_int.dtype)  # Output: int32


# Boolean (b):
# Creating an array of booleans
arr_bool = np.array([True, False, True], dtype='b')
print(arr_bool.dtype)  # Output: bool


# Unsigned integer (u):
# Creating an array of unsigned integers
arr_uint = np.array([0, 1, 2], dtype='uint32')  # Unsigned integers are specified with 'uint' followed by the number of bits
print(arr_uint.dtype)  # Output: uint32



# Float (f):
# Creating an array of floats
arr_float = np.array([1.0, 2.5, 3.7], dtype='f')
print(arr_float.dtype)  # Output: float32


# Complex float (C):
# Creating an array of complex floats
arr_complex = np.array([1 + 2j, 3 + 4j], dtype='complex128')
print(arr_complex.dtype)  # Output: complex128


# Timedelta (m):
# Creating an array of timedeltas
arr_timedelta = np.array([np.timedelta64(1, 'D'), np.timedelta64(2, 'D')], dtype='m')
print(arr_timedelta.dtype)  # Output: timedelta64[D]


# Datetime (M):
# Creating an array of datetimes
arr_datetime = np.array(['2024-06-03', '2024-06-04'], dtype='M')
print(arr_datetime.dtype)  # Output: datetime64[D]

# Object (O):
# Creating an array of objects
arr_object = np.array([1, 'two', 3.0], dtype='O')
print(arr_object.dtype)  # Output: object


# String (S):
# Creating an array of strings
arr_string = np.array(['apple', 'banana', 'cherry'], dtype='S')
print(arr_string.dtype)  # Output: |S6


# Unicode string (U):
# Creating an array of Unicode strings
arr_unicode = np.array(['apple', 'banana', 'cherry'], dtype='U')
print(arr_unicode.dtype)  # Output: <U6


# Void (V):
# Creating an array of void (empty) values
arr_void = np.array([(), (), ()], dtype='V')
print(arr_void.dtype)  # Output: void

int32
int8
uint32
float32
complex128
timedelta64[D]
datetime64[D]
object
|S6
<U6
|V8


In [192]:
import numpy as np 
arr_1 = np.array([1,2,3,4,5,6])
print("data type arr_1: ",arr_1.dtype)


arr_2 = np.array(["a","b","c","d","e","f"])
print("data type arr_2: ",arr_2.dtype)



arr_3 = np.array(["a","b","c","d","e","f",1,2,3,4,5,6])
print("data type arr_3: ",arr_3.dtype)

data type arr_1:  int32
data type arr_2:  <U1
data type arr_3:  <U11


In [195]:
# Now we want mention the data type when taking input like this,
y = np.array([1,2,3,4],dtype = np.int8)
print("data type",y.dtype)
print(y)

y1= np.array([1,2,3,4],dtype = "f")
print("data type",y1.dtype)
print()
print(y1)
print()

x1 = np.array([1,2,3,4],dtype = np.int8)
new  = np.float32(x1)
print("data type for x1 : ",x1.dtype)
print("data type for new : ",new.dtype)
print(x1)
print()
print(new)
print()




x2 = np.array([1,2,3,4],dtype = np.int8)
new  = np.float32(x2)
new_one = np.int_(new)
print("data type for x1 : ",x2.dtype)
print("data type for new : ",new.dtype)
print("data type for new_one : ",new_one.dtype)
print(x2)
print()
print(new)
print()
print(new_one)

data type int8
[1 2 3 4]
data type float32

[1. 2. 3. 4.]

data type for x1 :  int8
data type for new :  float32
[1 2 3 4]

[1. 2. 3. 4.]

data type for x1 :  int8
data type for new :  float32
data type for new_one :  int32
[1 2 3 4]

[1. 2. 3. 4.]

[1 2 3 4]


In [30]:
new_arr = np.array([1,2,3,4])
new_out = new_arr.astype(float)
print(new_arr)
print(new_out)

[1 2 3 4]
[1. 2. 3. 4.]


# Shape & Reshaping in Numpy Arrays

## Shape


In [31]:
import numpy as np 
arr_new = np.array([[1,2,8,9],[3,4,6,7]])
print(arr_new)
print()
print(arr_new.shape)

[[1 2 8 9]
 [3 4 6 7]]

(2, 4)


In [32]:
import numpy as np 
arr_n1 = np.array([8,9,6,7,4], ndmin=4)
print(arr_n1)
print(arr_n1.ndim)
print(arr_n1.shape)


[[[[8 9 6 7 4]]]]
4
(1, 1, 1, 5)


## Reshape

In [33]:
import numpy as np 
arr_n2 =np.array([7,5,8,6,1,3])
arr_o1 = arr_n2.reshape(3,2)


print(arr_n2)
print("dimension of arr_n2 : ",arr_n2.ndim)



print(arr_o1)
print("dimension of arr_o1 : ",arr_o1.ndim)


[7 5 8 6 1 3]
dimension of arr_n2 :  1
[[7 5]
 [8 6]
 [1 3]]
dimension of arr_o1 :  2


In [34]:
print("shape of arr_n2 : ",arr_n2.shape)
print("shape of arr_o1 : ",arr_o1.shape)

shape of arr_n2 :  (6,)
shape of arr_o1 :  (3, 2)


In [35]:
import numpy as np 
arr_m1 = np.array([34,15,58,26,31,48,79,58,14])

# reshaping the array of arr_m1
arr_m2 = arr_m1.reshape(3,3)

print(arr_m1)
print("dimention off arr_m1: ",arr_m1.ndim)
print("shape of array: ",arr_m1.shape)
print(arr_m2)

[34 15 58 26 31 48 79 58 14]
dimention off arr_m1:  1
shape of array:  (9,)
[[34 15 58]
 [26 31 48]
 [79 58 14]]


In [36]:
import numpy as np 
arr_d1 = np.array([16,52,48,37,54,26,12,64,79,63,44,51,52,74,89,15,26,14,18,13,15,16,36,38])
arr_d2 = arr_d1.reshape(8,3)
print(arr_d1)
print(arr_d2)
print(arr_d2.reshape(-1))

[16 52 48 37 54 26 12 64 79 63 44 51 52 74 89 15 26 14 18 13 15 16 36 38]
[[16 52 48]
 [37 54 26]
 [12 64 79]
 [63 44 51]
 [52 74 89]
 [15 26 14]
 [18 13 15]
 [16 36 38]]
[16 52 48 37 54 26 12 64 79 63 44 51 52 74 89 15 26 14 18 13 15 16 36 38]


# Arithmetic Operation in NumPy Arrays

* a+b  --------------------------------  np.add(a,b)
* a-b  --------------------------------  np.subtract(a,b)
* a*b  --------------------------------  np.multiply(a,b)
* a/b  --------------------------------  np.divide(a,b)
* a%b  --------------------------------  np.mod(a,b)
* a**b --------------------------------  np.power(a,b)
* 1/a  --------------------------------  np.reciprocal(a)

In [37]:
import numpy as np 
# a+b  --------------------------------  np.add(a,b)
arr1 = np.add(25,5)
print(arr1)

# a-b  --------------------------------  np.subtract(a,b)
arr1 = np.subtract(25,5)
print(arr1)

# a*b  --------------------------------  np.multiply(a,b)
arr1 = np.multiply(25,5)
print(arr1)

# a/b  --------------------------------  np.divide(a,b)
arr1 =  np.divide(25,5)
print (arr1)

# a%b  --------------------------------  np.mod(a,b)
arr1 = np.mod(25,5)
print(arr1)

# a**b --------------------------------  np.power(a,b)
arr1 = np.power(25,5)
print(arr1)

# 1/a  --------------------------------  np.reciprocal(a)

arr1 = np.reciprocal(5)

30
20
125
5.0
0
9765625


## * Arithmetic Operation apply on 1' dimention array

In [38]:
import numpy as np 
arr_j1 = np.array([9,7,2,6])
arr_j2 = np.array([5,7,9,4])

arr_j3 = arr_j1 + 3
print(arr_j3)

arr_j4 = arr_j1 + arr_j2
print(arr_j4)


[12 10  5  9]
[14 14 11 10]


In [39]:
import numpy as np
arr_p1 = np.array([9,7,2,6])
arr_p2 = np.array([5,7,9,4])

arr_p3 = arr_p1 - 3
print(arr_p3)

arr_p4 = arr_p1 - arr_p2
print(arr_p4)

[ 6  4 -1  3]
[ 4  0 -7  2]


In [40]:
import numpy as np
arr_q1 = np.array([9,7,2,6])
arr_q2 = np.array([5,7,9,4])

arr_q3 = arr_q1 * 3
print(arr_q3)

arr_q4 = arr_q1 * arr_q2
print(arr_q4)

[27 21  6 18]
[45 49 18 24]


In [41]:
import numpy as np
arr_q1 = np.array([9,7,2,6])
arr_q2 = np.array([5,7,9,4])

arr_q3 = arr_q1 / 3
print(arr_q3)

arr_q4 = arr_q1 / arr_q2
print(arr_q4)

[3.         2.33333333 0.66666667 2.        ]
[1.8        1.         0.22222222 1.5       ]


In [42]:
import numpy as np
arr_q1 = np.array([9,7,2,6])
arr_q2 = np.array([5,7,9,4])

arr_q3 = arr_q1 % 3
print(arr_q3)

arr_q4 = arr_q1 % arr_q2
print(arr_q4)

[0 1 2 0]
[4 0 2 2]


In [43]:
import numpy as np
arr_q1 = np.array([9,7,2,6])
arr_q2 = np.array([5,7,9,4])

arr_q3 = arr_q1 ** 3
print(arr_q3)

arr_q4 = arr_q1 ** arr_q2
print(arr_q4)

[729 343   8 216]
[ 59049 823543    512   1296]


In [44]:
import numpy as np
arr_q1 = np.array([9,7,2,6])
arr_q2 = np.array([5,7,9,4])

arr_q3 = 1/arr_q1 
print(arr_q3)

arr_q4 = 1/(arr_q1 * arr_q2)
print(arr_q4)

[0.11111111 0.14285714 0.5        0.16666667]
[0.02222222 0.02040816 0.05555556 0.04166667]


##  * Arithmetic Operation apply on 2d dimention array

In [45]:
import numpy as np 
arr1 = np.array([[4,5,6],[9,7,3]])
arr2 = np.array([[4,5,6],[9,7,3]])
arr3 = arr1 + arr2
print(arr1)
print()
print(arr2)
print()
print(arr3)
# another way we can add
arr4 = np.add(arr1,arr2)
print()
print(arr4)

[[4 5 6]
 [9 7 3]]

[[4 5 6]
 [9 7 3]]

[[ 8 10 12]
 [18 14  6]]

[[ 8 10 12]
 [18 14  6]]


In [46]:
import numpy as np 
arr1 = np.array([[4,5,6],[9,7,3]])
arr2 = np.array([[1,2,3],[2,5,8]])
arr3 = np.reciprocal(arr1)
print(arr3)

[[0 0 0]
 [0 0 0]]


# * Arithmetic  Function

* Maximum  --------------------------------  np.min(x)
* Minimum  --------------------------------  np.max(x)
* mini argumnet  --------------------------------  np.argmin(x)
* squre root  --------------------------------  np.sqrt(x)
* sin  --------------------------------  np.sin(x)
* cos --------------------------------  np.cos(x)
* cumsum  --------------------------------  np.cumsum(x)

In [47]:
import numpy as  np 
arr1 = np.array([1,2,3,9,6,4,8])
print("Maximum value in this array: ",np.max(arr1))

Maximum value in this array:  9


In [48]:
import numpy as  np 
arr1 = np.array([1,2,3,9,6,4,8])
print("Minimum value in this array: ",np.min(arr1))

Minimum value in this array:  1


In [49]:
import numpy as np 
arr1 = np.array([[2,8,4],[9,5,1]])
print(arr1)
print("Minimum value in this array row wise: ",np.min(arr1, axis=1)) # here axis 1 is indicates the row 

[[2 8 4]
 [9 5 1]]
Minimum value in this array row wise:  [2 1]


In [50]:
import numpy as np 
arr1 = np.array([[2,8,4],[9,5,1]])
print(arr1)
print("Minimum value in this array column wise: ",np.min(arr1, axis=0)) # here axis 1 is indicates the column 

[[2 8 4]
 [9 5 1]]
Minimum value in this array column wise:  [2 5 1]


In [51]:
import numpy as np 
arr1 = np.array([[2,8,4],[9,5,1]])
print(arr1)
print("squre root of the value in this array column wise: ",np.sqrt(arr1)) # here axis 1 is indicates the column 

[[2 8 4]
 [9 5 1]]
squre root of the value in this array column wise:  [[1.41421356 2.82842712 2.        ]
 [3.         2.23606798 1.        ]]


In [52]:
import numpy as np 
arr1 = np.array([[2,8,4],[9,5,1]])
print(arr1)
print("sin value in this array column wise: ",np.sin(arr1))

[[2 8 4]
 [9 5 1]]
sin value in this array column wise:  [[ 0.90929743  0.98935825 -0.7568025 ]
 [ 0.41211849 -0.95892427  0.84147098]]


In [53]:
import numpy as np 
arr1 = np.array([[2,8,4],[9,5,1]])
print(arr1)
print("cumsum value in this array column wise: ",np.cumsum(arr1))

[[2 8 4]
 [9 5 1]]
cumsum value in this array column wise:  [ 2 10 14 23 28 29]


# Broadcasting in Numpy Arrays: 

In [54]:
import numpy as np 
arr1 = np.array([1,2,3,4])
arr2 = np.array([[7],[4],[9],[6]])
# here we can see that both array are  not have same value

print(arr1)
print(arr2)
print(arr1 + arr2)
print((arr1 + arr2).ndim)
print((arr1 + arr2).shape)

[1 2 3 4]
[[7]
 [4]
 [9]
 [6]]
[[ 8  9 10 11]
 [ 5  6  7  8]
 [10 11 12 13]
 [ 7  8  9 10]]
2
(4, 4)


In [55]:
import numpy as  np 
arr1 = np.array([[4],[5]])
arr2 = np.array([[2,5,8],[9,6,3]])
print(arr1.shape)
print(arr2.shape)

print(arr1 + arr2)

(2, 1)
(2, 3)
[[ 6  9 12]
 [14 11  8]]


# Indexing & slicing in NumPy Arrays

## Indexing NumPy Array------

In [56]:
# apply on one dimention arrays
import numpy as np 
arr1 = np.array([9,7,8,5,4])
print(arr1[-1])

4


In [57]:
import numpy as np
arr1 = np.array([[9,7,5],[3,6,4]])
print(arr1)
print("dimension of this array : ",arr1.ndim)

print("indexing array for element: ",arr1[0,1])

[[9 7 5]
 [3 6 4]]
dimension of this array :  2
indexing array for element:  7


In [58]:
import numpy as np 
# Define the array
arr1 = np.array([[[1, 7, 5, 9], [9, 2, 6, 7]], [[8, 2, 8, 6], [3, 9, 2, 7]]])

# Print the array
print(arr1)

# Print the number of dimensions
print("dimension of this array : ", arr1.ndim)
# indexing array for element 7
print("indexing array for element: ",arr1[0,0,1])

[[[1 7 5 9]
  [9 2 6 7]]

 [[8 2 8 6]
  [3 9 2 7]]]
dimension of this array :  3
indexing array for element:  7


## Sliceing in NumPy Array

In [59]:
import numpy as np 

v1 = []
for i in range(1, 5):
    int_1 = int(input("Enter a number: "))
    v1.append(int_1)

arr1 = np.array(v1)
print(arr1)

Enter a number:  1
Enter a number:  2
Enter a number:  32
Enter a number:  4


[ 1  2 32  4]


In [60]:
import numpy as np 

# Parameters
num_elements = 15 # Number of elements in the array
min_val = 1      # Minimum value (inclusive)
max_val = 20     # Maximum value (exclusive)
# min_val = 1    
# max_val = 9 
# Create an array of random integers within the specified range
arr1 = np.random.randint(min_val, max_val, size=num_elements)

# Print the array
print(arr1)
print()
print(arr1[2:])
print()
print(arr1[:3])
# Create a 2x2 array of random integers within the specified range
arr2 = np.random.randint(min_val, max_val, size=(2,2))

# Print the array
print(arr2)

print(arr2[0,1])

[10 16  8 18  7 16 19 13  8  9  9 10 13  3  7]

[ 8 18  7 16 19 13  8  9  9 10 13  3  7]

[10 16  8]
[[19 14]
 [ 6 17]]
14


In [61]:
import numpy as np 

# Parameters
num_elements = 15 # Number of elements in the array
min_val = 1      # Minimum value (inclusive)
max_val = 20     # Maximum value (exclusive)

arr2 = np.random.randint(min_val, max_val, size=(3,5))

# Print the array
print(arr2)
print(arr2[1,3:])

[[10  3 14 19 12]
 [11 13  7 13 11]
 [ 3 11  5 19  8]]
[13 11]


In [62]:
import numpy as np 

# Parameters
num_elements = 15 # Number of elements in the array
min_val = 1      # Minimum value (inclusive)
max_val = 20     # Maximum value (exclusive)

arr2 = np.random.randint(min_val, max_val, size=(3,5))

# Print the array
print(arr2)


[[12  9  5  3 15]
 [13 15  8  5  5]
 [ 2 17 12 17  1]]


# Iterating NumPy Array

In [63]:
import numpy as np 
# Iteraing process apply on one dimension array
arr1 = np.array([9,8,7,6,5,4])
print(arr1)
for i in arr1:
    print(i)

[9 8 7 6 5 4]
9
8
7
6
5
4


In [64]:
# Iteraing process apply on two dimension array
import numpy as np 
arr1 = np.array([[9,8,7,6],[1,2,3,4]])
print(arr1)
print()

for i in arr1:
    print(i)
print()
for j in arr1 :
    for k in j : 
        print(k)

[[9 8 7 6]
 [1 2 3 4]]

[9 8 7 6]
[1 2 3 4]

9
8
7
6
1
2
3
4


In [65]:
# Iteraing process apply on three dimension array
import numpy as np 
arr1 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(arr1)
print()

print()
for j in arr1 :
    for k in j :
        for l in  k:
            print(l)
       

[[[9 8 7 6]
  [1 2 3 4]]]


9
8
7
6
1
2
3
4


In [66]:
# Iteraing process apply on three dimension array using nditer function
import numpy as np 
# Iteraing process apply on one dimension array
arr1 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(arr1)
print()

print()
for i in np.nditer(arr1):
    print(i)
   
           
       

[[[9 8 7 6]
  [1 2 3 4]]]


9
8
7
6
1
2
3
4


In [67]:
# Iteraing process apply on three dimension array using nditer function
import numpy as np 
# Iteraing process apply on one dimension array
arr1 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(arr1)
print()

print()
for i in np.nditer(arr1):
    print(i)
   
           
       

[[[9 8 7 6]
  [1 2 3 4]]]


9
8
7
6
1
2
3
4


In [68]:
# Iteraing process apply on three dimension array using nditer function
import numpy as np 
# Iteraing process apply on one dimension array
arr1 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(arr1)
print()

print()
for i,d in np.ndenumerate(arr1):
    print(i,d)
   
           
       

[[[9 8 7 6]
  [1 2 3 4]]]


(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


# COPY VS VIEW in NumPy Array

In [69]:
# copy function use in numpy array
import numpy as np 
arr1 = np.array([1,2,3,4])
cpy = arr1.copy()
print("arr1",arr1)
print()
print("cpoy",cpy)

arr1 [1 2 3 4]

cpoy [1 2 3 4]


In [70]:
# view function use in numpy array 
import numpy as np 
arr1 = np.array([1,2,3,4])
viw = arr1.view()
print("arr1",arr1)
print()
print("view",viw)

arr1 [1 2 3 4]

view [1 2 3 4]


In [71]:
#  In copy function in numpy array we can chage or rplace data using indixing method, its does't effect copy data
import numpy as np 
arr1 = np.array([1,2,3,4])
cpy = arr1.copy()
arr1[1] = 20
print("arr1",arr1)
print()
print("cpoy",cpy)

arr1 [ 1 20  3  4]

cpoy [1 2 3 4]


In [72]:
# view function use in numpy array 
import numpy as np 
arr1 = np.array([1,2,3,4])
viw = arr1.view()
arr1[1] = 30
print("arr1",arr1)
print()
print("view",viw)

arr1 [ 1 30  3  4]

view [ 1 30  3  4]


# Join & Split function in NumPy Array 

In [73]:
# join array function in numpy array,where we can two or more  one-dimension array joined and create a new array
import numpy as np 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr =np.concatenate((arr1,arr2))
print("new array after joining: ",arr)

new array after joining:  [1 2 3 4 5 6 7 8]


In [74]:
# join array function in numpy array,where we can two or more  two-dimension array joined and create a new array
# ROW wise joining
import numpy as np 
arr1 = np.array([[1,2],[3,4]])
print("arr1",arr1)
print()
arr2 = np.array([[5,6],[7,8]])
print("arr2 :",arr2)
print()
arr_new =np.concatenate((arr1,arr2),axis=1)
print("new array after joining in row : ",arr_new)

arr1 [[1 2]
 [3 4]]

arr2 : [[5 6]
 [7 8]]

new array after joining in row :  [[1 2 5 6]
 [3 4 7 8]]


In [75]:
# join array function in numpy array,where we can two or more  two-dimension array joined and create a new array
# COLUMN wise joining
import numpy as np 
arr1 = np.array([[1,2],[3,4]])
print("arr1",arr1)
print()
arr2 = np.array([[5,6],[7,8]])
print("arr2 :",arr2)
print()
arr_new =np.concatenate((arr1,arr2),axis=0)
print("new array after joining in column : ",arr_new)

arr1 [[1 2]
 [3 4]]

arr2 : [[5 6]
 [7 8]]

new array after joining in column :  [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [76]:
# join array function in numpy array,where we can two or more  two-dimension array joined and create a new array
# STACK FUNCTION  column  wise joining
import numpy as np 
arr1 = np.array([[1,2],[3,4]])
print("arr1",arr1)
print()
arr2 = np.array([[5,6],[7,8]])
print("arr2 :",arr2)
print()
arr_new =np.stack((arr1,arr2),axis=0)
print("new array after joining in column : ",arr_new)

arr1 [[1 2]
 [3 4]]

arr2 : [[5 6]
 [7 8]]

new array after joining in column :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [77]:
import numpy as np 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr =np.hstack((arr1,arr2)) # row wise
print("new array after joining: ",arr)

new array after joining:  [1 2 3 4 5 6 7 8]


In [78]:
import numpy as np 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr =np.vstack((arr1,arr2)) # column wise 
print("new array after joining: ",arr)

new array after joining:  [[1 2 3 4]
 [5 6 7 8]]


In [79]:
import numpy as np 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr =np.dstack((arr1,arr2))# height wise 
print("new array after joining: ",arr)

new array after joining:  [[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [80]:
import numpy as np 
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
arr_new = np.array_split(arr1,3)
print(arr_new)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [81]:
import numpy as np 

arr1 = np.array([[1, 2, 3, 4, 5, 6],
                 [7, 8, 9, 10, 11, 12]])
print("Original array:")
print(arr1)

# Split the array into 3 parts along axis 1 (columns)
arr_new = np.array_split(arr1, 3, axis=1)
print("Splitted array along axis 1:")
print(arr_new)


Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Splitted array along axis 1:
[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]


# Search

## where() function

In [82]:
# how to search a element in a array  where function
import numpy as np 
arr1 = np.array([4,2,3,4,2,5,2,5,6,7])
# index number   0,1,2,3,4,5,6,7,8,9
arr2 = np.where((arr1/2) == 2)
print(arr2)

(array([0, 3], dtype=int64),)


## searchsorted() function

In [83]:
# how to search a element in a array 
import numpy as np 
arr1 = np.array([4,2,3,4,2,5,2,5,6,7])
# index number   0,1,2,3,4,5,6,7,8,9
arr2 = np.searchsorted(arr1,5)
print(arr2)

5


In [87]:
import numpy as np 
arr1 = np.array([1,2,3,4,8,9,10])
# index number   0,1,2,3,4,5,6,7,8,9
arr2 = np.searchsorted(arr1,[5,6,7],side="right")
print(arr2)

[4 4 4]


## sort() function

In [89]:
# how to search a element in a array 
import numpy as np 
arr1 = np.array([4,2,3,12,2,15,22,5,6,7])
# index number   0,1,2,3,4,5,6,7,8,9
arr2 = np.sort(arr1)
print(arr2)

[ 2  2  3  4  5  6  7 12 15 22]


In [91]:
# how to search a element in a array 
import numpy as np 
arr1 = np.array(["a","q","h","n","m","b","d","i","f","c"])
# index number   0,1,2,3,4,5,6,7,8,9
arr2 = np.sort(arr1)
print(arr2)

['a' 'b' 'c' 'd' 'f' 'h' 'i' 'm' 'n' 'q']


In [100]:
import numpy as np
arr1 = np.array([[1,8,5],[2,3,6],[3,8,2],[4,7,8]])
print("original array: ",arr1)
print()

arr2 = np.sort(arr1)
print("after sorting the array: ",arr2)
print("Shape of this array: ",arr1.shape)
print("dimension so this array: ",arr1.ndim)

original array:  [[1 8 5]
 [2 3 6]
 [3 8 2]
 [4 7 8]]

after sorting the array:  [[1 5 8]
 [2 3 6]
 [2 3 8]
 [4 7 8]]
Shape of this array:  (4, 3)
dimension so this array:  2


## filter() function 

In [103]:
import numpy as np
arr1 = np.array(["a","q","h","n"])
arr2 = [True,False,False,True]
arr_new = arr1[arr2]
print(arr_new)
print("Type of this array: ",type(arr_new))

['a' 'n']
Type of this array:  <class 'numpy.ndarray'>


# NumPy Array Function
## Shuffle,Unique,Resize,Flatten,Reavel Function

In [106]:
# Shuffle function 
import numpy as np 
arr1 = np.array([1,2,3,4,5])
np.random.shuffle(arr1)
print(arr1)

[4 1 2 3 5]


In [107]:
# Unique function 
import numpy as  np
arr1 = np.array([1,2,3,4,5,2,6,2,7])
arr2 = np.unique(arr1)
print(arr2)

[1 2 3 4 5 6 7]


In [108]:
#  if we want to see index of unique arrays elements  so, here we using Unique function 
import numpy as  np
arr1 = np.array([1,2,3,4,5,2,6,2,7])
arr2 = np.unique(arr1,return_index=True)
print(arr2)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 6, 8], dtype=int64))


In [109]:
#  if we want to see index of unique arrays elements  so, here we using Unique function 
import numpy as  np
arr1 = np.array([1,2,3,4,5,2,6,2,7])
arr2 = np.unique(arr1,return_index=True,return_counts=True)
print(arr2)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 6, 8], dtype=int64), array([1, 3, 1, 1, 1, 1, 1], dtype=int64))


In [124]:
# Resize function
import numpy as  np
arr1 = np.array([1,2,3,4,5,2,6,2,7])
arr = np.resize(arr1,(3,3))
print(arr)


[[1 2 3]
 [4 5 2]
 [6 2 7]]


In [117]:
# Flatten functiop - its use to convert 2d array to 1d array
import numpy as  np
arr1 = np.array([[1,8,5],[2,3,6],[3,8,2],[4,7,8]])
arr = np.resize(arr1,(3,4))
print(arr1) 
print()
print("Flatten: ",arr.flatten(order = "F"))

[[1 8 5]
 [2 3 6]
 [3 8 2]
 [4 7 8]]

Flatten:  [1 3 2 8 6 4 5 3 7 2 8 8]


## Arithmetic Functions
## **Order: {'C', 'F', 'A', 'K'}, Optional
* 'C' means to flatten in row-major (C-style) order.
* 'F' means to flatten in column-major (Fortran-style) order.
* 'A' means to flatten in column-major order if `a` is Fortran *contiguous* in memory, row-major order otherwise.
* 'K' means to flatten `a` in the order the elements occur in memor
* The default is 'C'.

In [123]:
# Flatten functiop - its use to convert 2d array to 1d array
import numpy as  np
arr1 = np.array([1,2,3,4,5,6,7])
arr = np.resize(arr1,(3,2))
print(arr1) 
print()
print("Flatten Function C: ",arr.flatten(order = "C"))
print("Flatten Function F: ",arr.flatten(order = "F"))
print("Flatten Function A: ",arr.flatten(order = "A"))
print("Flatten Function K: ",arr.flatten(order = "K"))
print()
print("Ravel Function C: ",np.ravel(arr,order = "C"))
print("Ravel Function F: ",np.ravel(arr,order = "F"))
print("Ravel Function A: ",np.ravel(arr,order = "A"))
print("Ravel Function K: ",np.ravel(arr,order = "K"))

[1 2 3 4 5 6 7]

Flatten Function C:  [1 2 3 4 5 6]
Flatten Function F:  [1 3 5 2 4 6]
Flatten Function A:  [1 2 3 4 5 6]
Flatten Function K:  [1 2 3 4 5 6]

Ravel Function C:  [1 2 3 4 5 6]
Ravel Function F:  [1 3 5 2 4 6]
Ravel Function A:  [1 2 3 4 5 6]
Ravel Function K:  [1 2 3 4 5 6]


# NumPy Arrays Functiona (Insert and Delete Function)

In [129]:
import numpy as np 
arr1 = np.array([1,2,3,4])
# index number   0,1,2,3,4,5,6,7,8,9
arr_new = np.insert(arr1,2,40)
print(arr1)
print(arr_new)
print(arr1.dtype)
print(type(arr1))

[1 2 3 4]
[ 1  2 40  3  4]
int32
<class 'numpy.ndarray'>


In [130]:
import numpy as np 
arr1 = np.array([1,2,3,4])
# index number   0,1,2,3,4,5,6,7,8,9
arr_new = np.insert(arr1,[2,4],40)
print(arr1)
print(arr_new)
print(arr1.dtype)
print(type(arr1))

[1 2 3 4]
[ 1  2 40  3  4 40]
int32
<class 'numpy.ndarray'>


In [136]:
import numpy as np 
arr1 = np.array([[1,2,3],[1,2,3]])
arr_new = np.insert(arr1,2,40,axis=1)
print(arr1)
print()
print(arr_new)

[[1 2 3]
 [1 2 3]]

[[ 1  2 40  3]
 [ 1  2 40  3]]


In [138]:
# using append function we can insert elements into the array in last positiona
import numpy as np 
arr1 = np.array([[1,2,3],[1,2,3]])
arr_new = np.append(arr1,9.4)
print(arr1)
print()
print(arr_new)

[[1 2 3]
 [1 2 3]]

[1.  2.  3.  1.  2.  3.  9.4]


In [140]:
# using append function we can insert elements into the array in last positiona
import numpy as np 
arr1 = np.array([[1,2,3],[1,2,3]])
arr_new = np.append(arr1,[[45,23,65]],axis=0)
print(arr1)
print()
print(arr_new)

[[1 2 3]
 [1 2 3]]

[[ 1  2  3]
 [ 1  2  3]
 [45 23 65]]


In [141]:
# using append function we can delete elements into the array in last positiona
import numpy as np 
arr1 = np.array([[1,2,3],[1,2,3]])
arr_new = np.append(arr1,[[45,23,65]],axis=0)
print(arr1)
print()
print(arr_new)

[[1 2 3]
 [1 2 3]]

[[ 1  2  3]
 [ 1  2  3]
 [45 23 65]]
